function [p00,p11,p22,p33,v00,v11,v22,v33] = autoGen_3InvPenKinematics(q0,q1,q2,q3,q0d,q1d,q2d,q3d,empty)
%AUTOGEN_3INVPENKINEMATICS
%    [P00,P11,P22,P33,V00,V11,V22,V33] = AUTOGEN_3INVPENKINEMATICS(Q0,Q1,Q2,Q3,Q0D,Q1D,Q2D,Q3D,EMPTY)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    31-Mar-2019 17:27:57

p00 = [q0;empty];
if nargout > 1
    t2 = sin(q1);
    t3 = cos(q1);
    t4 = t3.*(8.0./2.5e1);
    p11 = [q0-t2.*(8.0./2.5e1);t4];
end
if nargout > 2
    t5 = sin(q2);
    t6 = cos(q2);
    t7 = t6.*(4.19e2./1.0e3);
    p22 = [q0-t2.*(8.0./2.5e1)-t5.*(4.19e2./1.0e3);t4+t7];
end
if nargout > 3
    t8 = cos(q3);
    t9 = sin(q3);
    p33 = [q0-t2.*(8.0./2.5e1)-t5.*(4.19e2./1.0e3)-t9.*(9.7e1./2.0e2);t4+t7+t8.*(9.7e1./2.0e2)];
end
if nargout > 4
    v00 = [q0d;empty];
end
if nargout > 5
    v11 = [q0d-q1d.*t3.*(8.0./2.5e1);q1d.*t2.*(-8.0./2.5e1)];
end
if nargout > 6
    v22 = [q0d-q1d.*t3.*(8.0./2.5e1)-q2d.*t6.*(4.19e2./1.0e3);q1d.*t2.*(-8.0./2.5e1)-q2d.*t5.*(4.19e2./1.0e3)];
end
if nargout > 7
    v33 = [q0d-q1d.*t3.*(8.0./2.5e1)-q2d.*t6.*(4.19e2./1.0e3)-q3d.*t8.*(9.7e1./2.0e2);q1d.*t2.*(-8.0./2.5e1)-q2d.*t5.*(4.19e2./1.0e3)-q3d.*t9.*(9.7e1./2.0e2)];
end
